#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")
Import("env_modules")

env_mcp = env_modules.Clone()

# Add source files
env_mcp.add_source_files(env.modules_sources, "*.cpp")
env_mcp.add_source_files(env.modules_sources, "tools/*.cpp")

# Add editor plugin if tools are enabled
if env.editor_build:
    env_mcp.add_source_files(env.modules_sources, "editor/*.cpp")
